### ISSUE TITLE
请问要如何更换网址 那个 b站网址现在是 点选了

### ISSUE THREAD

**Issue by 3215656174** [Aruelius/geetest_track#2]

**Comment by 3215656174** [comment]
大佬 更改了之后 发现它一直不断访问http://127.0.0.1:5000/bilibili/combine?t=时间戳 就是不获取到滑块

**Comment by Aruelius** [comment]
推测应该是极验官方的 DEMO 接口和本项目里的 JS 文件版本不对应，我换了个春秋航空的极验接口~

**Comment by 3215656174** [comment]
嗯嗯 现在可以获取到滑块了 大佬请问一下 这个轨迹我获取到之后 给软件去调用 然后 最后提交的时候 还是显示forbben 是咋回事

**Comment by Aruelius** [comment]
你要自己筛选这个轨迹能不能用，根据 x 坐标判断，看 README

**Comment by 3215656174** [comment]
嗯嗯谢谢大佬
